version: "3"
services:
  authms:
    container_name: authms
    build:
      context: .
    env_file: .env
    environment:
      - PORT=$PORT
      - KEY=$KEY
      - JWT_SECRET=$JWT_SECRET
      - DB_URL=$DB_URL
    links:
      - mongodb
    ports:
      - 3000:3000
  mongodb:
    container_name: mongodb
    image: mongo
    ports: 
      - 27017:27017
